const prefectures = [
  ["Hokkaido", "hokkaido", "Furano and Biei", "Wide flower fields, snow scenery, and road-trip landscapes.", ["nature", "snow", "flowers"]],
  ["Aomori", "tohoku", "Hirosaki Castle", "Cherry blossoms, castle history, apple country, and northern festival culture.", ["spring", "castle", "festival"]],
  ["Iwate", "tohoku", "Hiraizumi", "Calm temple heritage and gardens for a slower cultural stop.", ["heritage", "temples", "slow"]],
  ["Miyagi", "tohoku", "Matsushima Bay", "Island views, bay cruises, seafood, and an easy Sendai side trip.", ["coast", "seafood", "views"]],
  ["Akita", "tohoku", "Kakunodate", "Samurai houses, spring blossoms, and a quiet historical townscape.", ["history", "spring", "old town"]],
  ["Yamagata", "tohoku", "Yamadera", "A mountain temple climb with valley views and a rewarding half-day route.", ["temple", "hiking", "views"]],
  ["Fukushima", "tohoku", "Ouchi-juku", "A thatched-roof post town with local noodles and old-road atmosphere.", ["old town", "food", "history"]],
  ["Ibaraki", "kanto", "Hitachi Seaside Park", "Seasonal flower hills, especially nemophila in spring and kochia in autumn.", ["flowers", "spring", "autumn"]],
  ["Tochigi", "kanto", "Nikko Toshogu Shrine", "Lavish shrine architecture, forested sacred sites, waterfalls, and onsen add-ons.", ["heritage", "shrines", "nature"]],
  ["Gunma", "kanto", "Kusatsu Onsen", "A classic hot spring town centered around steaming yubatake fields.", ["onsen", "winter", "slow"]],
  ["Saitama", "kanto", "Kawagoe", "An easy Tokyo day trip with old storehouses, snacks, and Edo-period charm.", ["day trip", "old town", "food"]],
  ["Chiba", "kanto", "Naritasan Shinsho-ji", "A temple town near Narita Airport for arrival or departure day sightseeing.", ["temple", "airport", "day trip"]],
  ["Tokyo", "kanto", "Asakusa and Shibuya", "Old-town temple streets by day and neon city energy by night.", ["city", "food", "first trip"]],
  ["Kanagawa", "kanto", "Kamakura", "Coastal temples, the Great Buddha, hiking paths, and relaxed cafes near Tokyo.", ["coast", "temples", "day trip"]],
  ["Niigata", "chubu", "Sado Island", "Island culture, gold mine history, rugged coastlines, and slow travel.", ["island", "history", "slow"]],
  ["Toyama", "chubu", "Tateyama Kurobe Alpine Route", "Mountain transport, alpine scenery, and seasonal snow walls.", ["mountains", "snow", "scenery"]],
  ["Ishikawa", "chubu", "Kanazawa", "Gardens, craft culture, preserved districts, seafood, and a refined city pace.", ["gardens", "crafts", "food"]],
  ["Fukui", "chubu", "Dinosaur Museum", "A standout family museum with coastal and temple side trips nearby.", ["museum", "family", "coast"]],
  ["Yamanashi", "chubu", "Fuji Five Lakes", "Mt. Fuji views, lakeside stays, hot springs, and photography scenery.", ["fuji", "nature", "onsen"]],
  ["Nagano", "chubu", "Matsumoto and Kamikochi", "Original castle architecture plus alpine walking routes.", ["castle", "hiking", "mountains"]],
  ["Gifu", "chubu", "Shirakawa-go", "Thatched farmhouses, snowy scenes, and traditional village landscapes.", ["village", "heritage", "winter"]],
  ["Shizuoka", "chubu", "Izu Peninsula", "Coastal hot springs, beaches, seafood, and Mt. Fuji views.", ["coast", "onsen", "seafood"]],
  ["Aichi", "chubu", "Nagoya and Osu", "Miso cuisine, shopping arcades, castle history, and a practical city stop.", ["city", "food", "castle"]],
  ["Mie", "kansai", "Ise Jingu", "One of Japan's most important shrine areas, paired with old streets and coastal food.", ["shrines", "culture", "food"]],
  ["Shiga", "kansai", "Lake Biwa", "Japan's largest lake with cycling, castle towns, temples, and water views.", ["lake", "cycling", "slow"]],
  ["Kyoto", "kansai", "Arashiyama and Higashiyama", "Iconic temples, bamboo, gardens, tea culture, and heritage walks.", ["temples", "culture", "first trip"]],
  ["Osaka", "kansai", "Dotonbori and Shinsekai", "Casual food, nightlife, and a friendly base for Kansai day trips.", ["food", "nightlife", "city"]],
  ["Hyogo", "kansai", "Himeji Castle", "Japan's most famous original castle, easy to combine with Kobe or Osaka.", ["castle", "heritage", "day trip"]],
  ["Nara", "kansai", "Nara Park and Todai-ji", "Ancient capital atmosphere, huge temple architecture, parkland, and easy walking.", ["temples", "history", "family"]],
  ["Wakayama", "kansai", "Koyasan", "Temple lodging, forested pilgrimage atmosphere, and a deeper side of Kansai.", ["temple stay", "pilgrimage", "slow"]],
  ["Tottori", "chugoku", "Tottori Sand Dunes", "Large dunes, coastal views, and a landscape that surprises visitors.", ["coast", "nature", "unique"]],
  ["Shimane", "chugoku", "Izumo Taisha", "A major shrine with mythology, quiet streets, and strong cultural identity.", ["shrines", "mythology", "culture"]],
  ["Okayama", "chugoku", "Kurashiki Bikan Quarter", "Canals, white-walled storehouses, museums, and slow-travel town scenery.", ["old town", "museums", "slow"]],
  ["Hiroshima", "chugoku", "Peace Memorial Park and Miyajima", "A meaningful history stop paired with island shrine scenery.", ["history", "island", "heritage"]],
  ["Yamaguchi", "chugoku", "Motonosumi Shrine", "A dramatic line of red torii gates facing the Sea of Japan.", ["shrine", "coast", "photo"]],
  ["Tokushima", "shikoku", "Iya Valley", "Vine bridges, deep valleys, and festival dance culture.", ["valley", "festival", "nature"]],
  ["Kagawa", "shikoku", "Naoshima and Takamatsu", "Art islands, gardens, ferries, and excellent Sanuki udon.", ["art", "islands", "food"]],
  ["Ehime", "shikoku", "Dogo Onsen", "Classic hot spring atmosphere with Matsuyama Castle nearby.", ["onsen", "castle", "slow"]],
  ["Kochi", "shikoku", "Shimanto River", "Clear river landscapes, markets, local food, and outdoor travel.", ["river", "nature", "food"]],
  ["Fukuoka", "kyushu", "Hakata and Yatai Food Stalls", "Ramen, street stalls, shopping, and a convenient Kyushu gateway.", ["food", "city", "gateway"]],
  ["Saga", "kyushu", "Arita and Imari", "Porcelain towns with kilns, craft shopping, and a calmer culture route.", ["crafts", "ceramics", "slow"]],
  ["Nagasaki", "kyushu", "Nagasaki City", "Harbor views, international history, churches, night scenery, and local food.", ["history", "harbor", "food"]],
  ["Kumamoto", "kyushu", "Kumamoto Castle and Aso", "Castle restoration, volcanic landscapes, grasslands, and road-trip routes.", ["castle", "volcano", "nature"]],
  ["Oita", "kyushu", "Beppu Onsen", "A steam-filled hot spring town with baths, hell tours, and easy access.", ["onsen", "food", "slow"]],
  ["Miyazaki", "kyushu", "Takachiho Gorge", "A dramatic gorge with mythology, boat rides, waterfalls, and rural scenery.", ["gorge", "mythology", "nature"]],
  ["Kagoshima", "kyushu", "Sakurajima", "An active volcano across the bay with ferries, views, and hot sand baths nearby.", ["volcano", "views", "onsen"]],
  ["Okinawa", "kyushu", "Kerama Islands", "Clear water, snorkeling, diving, island stays, and subtropical Japan.", ["islands", "beach", "diving"]],
];

const regionLabels = {
  en: {
    all: "All",
    hokkaido: "Hokkaido",
    tohoku: "Tohoku",
    kanto: "Kanto",
    chubu: "Chubu",
    kansai: "Kansai",
    chugoku: "Chugoku",
    shikoku: "Shikoku",
    kyushu: "Kyushu + Okinawa",
  },
  ja: {
    all: "すべて",
    hokkaido: "北海道",
    tohoku: "東北",
    kanto: "関東",
    chubu: "中部",
    kansai: "関西",
    chugoku: "中国",
    shikoku: "四国",
    kyushu: "九州・沖縄",
  },
  zh: {
    all: "全部",
    hokkaido: "北海道",
    tohoku: "东北",
    kanto: "关东",
    chubu: "中部",
    kansai: "关西",
    chugoku: "中国地方",
    shikoku: "四国",
    kyushu: "九州・冲绳",
  },
  ko: {
    all: "전체",
    hokkaido: "홋카이도",
    tohoku: "도호쿠",
    kanto: "간토",
    chubu: "주부",
    kansai: "간사이",
    chugoku: "주고쿠",
    shikoku: "시코쿠",
    kyushu: "규슈・오키나와",
  },
  fr: {
    all: "Tous",
    hokkaido: "Hokkaido",
    tohoku: "Tohoku",
    kanto: "Kanto",
    chubu: "Chubu",
    kansai: "Kansai",
    chugoku: "Chugoku",
    shikoku: "Shikoku",
    kyushu: "Kyushu + Okinawa",
  },
  it: {
    all: "Tutte",
    hokkaido: "Hokkaido",
    tohoku: "Tohoku",
    kanto: "Kanto",
    chubu: "Chubu",
    kansai: "Kansai",
    chugoku: "Chugoku",
    shikoku: "Shikoku",
    kyushu: "Kyushu + Okinawa",
  },
};

const translations = {
  en: {
    htmlLang: "en",
    brand: "Japan Prefecture Travel Guide",
    languageLabel: "Language",
    navRoutes: "Routes",
    navPrefectures: "Prefectures",
    navPlanning: "Planning",
    heroEyebrow: "Japan travel ideas for international visitors",
    heroTitle: "A practical travel guide to all 47 prefectures of Japan.",
    heroText:
      "Explore one carefully selected spot for every prefecture, then use route ideas and planning notes to build a trip that goes beyond the usual first-time itinerary.",
    heroButton: "Explore 47 prefectures",
    summaryPrefectures: "prefecture travel ideas",
    summaryRegions: "available languages",
    summarySpot: "starter route ideas",
    routesEyebrow: "Suggested routes",
    routesTitle: "Start with a route, then choose prefectures that fit your style.",
    routesText:
      "These route ideas help visitors connect the prefecture cards into a real trip. They are intentionally broad, so travelers can adapt them to budget, season, and transport options.",
    route1Label: "First visit",
    route1Title: "Tokyo, Kyoto, Osaka and Nara",
    route1Text: "A balanced introduction with city energy, temples, food streets and easy train connections.",
    route2Label: "Culture and coast",
    route2Title: "Kanazawa, Kyoto, Hiroshima and Miyajima",
    route2Text: "A slower route for gardens, craft districts, historic neighborhoods and island shrine scenery.",
    route3Label: "Nature add-on",
    route3Title: "Mt. Fuji, Hokkaido or Okinawa",
    route3Text: "Add mountains, snow, hot springs or islands when you want a trip beyond big cities.",
    pickerEyebrow: "Travel picker",
    pickerTitle: "Explore Japan by prefecture.",
    pickerText:
      "Each card highlights one recommended place and the kind of traveler it suits. Use search for themes such as food, onsen, islands, castles, temples, nature and seasonal scenery.",
    searchLabel: "Search",
    searchPlaceholder: "Try Fuji, onsen, food, island...",
    countSingular: "prefecture shown",
    countPlural: "prefectures shown",
    cardIntro: "A simple pick for travelers interested in",
    nextEyebrow: "Planning notes",
    nextTitle: "Use the guide as a starting point, then check official details before booking.",
    nextText:
      "Opening hours, transport routes, weather risks and event dates can change. Before booking hotels, tickets or tours, confirm the latest information with official tourism and transport sources.",
    nextCard1Title: "Choose by travel purpose",
    nextCard1Text: "City food, temples, islands, snow, hot springs and craft towns all suit different trip styles.",
    nextCard2Title: "Check timing and transport",
    nextCard2Text: "Seasonal flowers, snow routes, ferries and rural buses often require extra planning.",
    nextCard3Title: "Travel respectfully",
    nextCard3Text: "Follow local signs for photography, trash, smoking areas, shrine manners and crowded neighborhoods.",
    footerBrand: "Japan Prefecture Travel Guide",
    footerText: "Independent travel planning content for international visitors. Always verify live details before booking.",
  },
  ja: {
    htmlLang: "ja",
    brand: "日本47都道府県トラベルガイド",
    languageLabel: "言語",
    navRoutes: "ルート",
    navPrefectures: "都道府県",
    navPlanning: "計画",
    heroEyebrow: "訪日旅行者向けの日本旅行アイデア",
    heroTitle: "日本47都道府県をめぐる実用トラベルガイド。",
    heroText:
      "各都道府県から編集済みのおすすめスポットを1つずつ紹介し、ルート案と旅行メモで初回旅行の定番だけではない日本旅を組み立てられるようにします。",
    heroButton: "47都道府県を見る",
    summaryPrefectures: "都道府県の旅行案",
    summaryRegions: "対応言語",
    summarySpot: "旅程ルート案",
    routesEyebrow: "おすすめルート",
    routesTitle: "まずルートを選び、旅のスタイルに合う都道府県を探す。",
    routesText:
      "都道府県カードを実際の旅程につなげるためのルート案です。予算、季節、交通手段に合わせて調整しやすいよう、広めの構成にしています。",
    route1Label: "初めての日本",
    route1Title: "東京・京都・大阪・奈良",
    route1Text: "都市、寺社、食べ歩き、鉄道移動をバランスよく体験できる定番ルートです。",
    route2Label: "文化と海",
    route2Title: "金沢・京都・広島・宮島",
    route2Text: "庭園、工芸、歴史ある町並み、島の神社風景をゆっくり楽しむルートです。",
    route3Label: "自然を追加",
    route3Title: "富士山・北海道・沖縄",
    route3Text: "大都市以外に、山、雪、温泉、島を加えたい旅行者向けの選択肢です。",
    pickerEyebrow: "旅行スポット検索",
    pickerTitle: "都道府県から日本を探す。",
    pickerText:
      "各カードでは、おすすめスポットと向いている旅行スタイルを紹介しています。食、温泉、島、城、寺社、自然、季節の景色などで検索できます。",
    searchLabel: "検索",
    searchPlaceholder: "例: Fuji, onsen, food, island...",
    countSingular: "件を表示中",
    countPlural: "件を表示中",
    cardIntro: "旅行者におすすめ。テーマ:",
    nextEyebrow: "旅行計画メモ",
    nextTitle: "このガイドを出発点にし、予約前に公式情報を確認する。",
    nextText:
      "営業時間、交通、天候、イベント日程は変わることがあります。ホテル、チケット、ツアーを予約する前に、公式観光情報や交通機関の最新情報を確認してください。",
    nextCard1Title: "旅の目的で選ぶ",
    nextCard1Text: "都市グルメ、寺社、島、雪、温泉、工芸の町など、旅のスタイルごとに向く場所が変わります。",
    nextCard2Title: "時期と交通を確認",
    nextCard2Text: "花の見頃、雪のルート、フェリー、地方バスは事前確認が大切です。",
    nextCard3Title: "地域に配慮して旅する",
    nextCard3Text: "写真撮影、ゴミ、喫煙、神社参拝、混雑する住宅地では現地の案内に従ってください。",
    footerBrand: "日本47都道府県トラベルガイド",
    footerText: "訪日旅行者向けの独立した旅行計画コンテンツです。予約前には必ず最新情報を確認してください。",
  },
  zh: {
    htmlLang: "zh",
    brand: "日本都道府县旅行指南",
    languageLabel: "语言",
    navRoutes: "路线",
    navPrefectures: "都道府县",
    navPlanning: "规划",
    heroEyebrow: "面向访日游客的日本旅行灵感",
    heroTitle: "面向日本47个都道府县的实用旅行指南。",
    heroText:
      "每个都道府县精选一个推荐地点，并提供路线灵感和旅行提示，帮助你规划不只停留在经典路线的日本之旅。",
    heroButton: "浏览47个都道府县",
    summaryPrefectures: "都道府县旅行灵感",
    summaryRegions: "支持语言",
    summarySpot: "入门路线建议",
    routesEyebrow: "推荐路线",
    routesTitle: "先选择路线，再挑选适合你旅行风格的都道府县。",
    routesText:
      "这些路线能把都道府县卡片连接成真实行程，并可根据预算、季节和交通方式调整。",
    route1Label: "首次访问",
    route1Title: "东京、京都、大阪和奈良",
    route1Text: "适合第一次来日本，兼顾城市活力、寺庙、美食街和便利铁路。",
    route2Label: "文化与海岸",
    route2Title: "金泽、京都、广岛和宫岛",
    route2Text: "适合庭园、工艺、历史街区和海岛神社风景的慢旅行。",
    route3Label: "自然延伸",
    route3Title: "富士山、北海道或冲绳",
    route3Text: "想在大城市之外加入山景、雪景、温泉或岛屿时，可以选择这些方向。",
    pickerEyebrow: "旅行选择器",
    pickerTitle: "按都道府县探索日本。",
    pickerText:
      "每张卡片都介绍一个推荐地点和适合的旅行风格。你可以搜索美食、温泉、岛屿、城堡、寺庙、自然和季节风景。",
    searchLabel: "搜索",
    searchPlaceholder: "试试 Fuji, onsen, food, island...",
    countSingular: "个都道府县显示中",
    countPlural: "个都道府县显示中",
    cardIntro: "适合对这些主题感兴趣的旅行者:",
    nextEyebrow: "旅行规划提示",
    nextTitle: "把本指南作为起点，预订前请确认官方最新信息。",
    nextText: "营业时间、交通路线、天气风险和活动日期可能变化。预订酒店、门票或行程前，请查看官方旅游和交通信息。",
    nextCard1Title: "按旅行目的选择",
    nextCard1Text: "城市美食、寺庙、岛屿、雪景、温泉和工艺小镇适合不同旅行风格。",
    nextCard2Title: "确认季节和交通",
    nextCard2Text: "花季、雪季路线、渡轮和乡村巴士通常需要提前规划。",
    nextCard3Title: "尊重当地旅行",
    nextCard3Text: "拍照、垃圾、吸烟、神社礼仪和拥挤街区，请遵守当地指示。",
    footerBrand: "日本都道府县旅行指南",
    footerText: "面向访日游客的独立旅行规划内容。预订前请务必确认最新信息。",
  },
  ko: {
    htmlLang: "ko",
    brand: "일본 도도부현 여행 가이드",
    languageLabel: "언어",
    navRoutes: "루트",
    navPrefectures: "도도부현",
    navPlanning: "여행 계획",
    heroEyebrow: "방일 여행자를 위한 일본 여행 아이디어",
    heroTitle: "일본 47개 도도부현을 위한 실용 여행 가이드.",
    heroText:
      "도도부현마다 엄선한 추천 장소를 소개하고, 루트 아이디어와 여행 메모로 일반적인 첫 일본 여행을 넘어서는 일정을 만들 수 있게 돕습니다.",
    heroButton: "47개 도도부현 보기",
    summaryPrefectures: "도도부현 여행 아이디어",
    summaryRegions: "지원 언어",
    summarySpot: "시작 루트 아이디어",
    routesEyebrow: "추천 루트",
    routesTitle: "먼저 루트를 고르고, 여행 스타일에 맞는 도도부현을 선택하세요.",
    routesText:
      "이 루트 아이디어는 도도부현 카드를 실제 여행 일정으로 연결해 줍니다. 예산, 계절, 교통에 맞게 조정하기 쉽도록 넓게 구성했습니다.",
    route1Label: "첫 방문",
    route1Title: "도쿄, 교토, 오사카, 나라",
    route1Text: "도시 에너지, 사찰, 먹거리 거리, 편리한 철도를 균형 있게 경험하는 입문 루트입니다.",
    route2Label: "문화와 해안",
    route2Title: "가나자와, 교토, 히로시마, 미야지마",
    route2Text: "정원, 공예 거리, 역사적인 동네, 섬의 신사 풍경을 천천히 즐기는 루트입니다.",
    route3Label: "자연 추가",
    route3Title: "후지산, 홋카이도 또는 오키나와",
    route3Text: "대도시 외에 산, 눈, 온천, 섬을 더하고 싶을 때 좋은 선택입니다.",
    pickerEyebrow: "여행지 선택",
    pickerTitle: "도도부현별로 일본을 탐색하세요.",
    pickerText:
      "각 카드는 추천 장소와 어울리는 여행 스타일을 보여줍니다. 음식, 온천, 섬, 성, 사찰, 자연, 계절 풍경으로 검색할 수 있습니다.",
    searchLabel: "검색",
    searchPlaceholder: "예: Fuji, onsen, food, island...",
    countSingular: "개 도도부현 표시 중",
    countPlural: "개 도도부현 표시 중",
    cardIntro: "이런 테마에 관심 있는 여행자에게 추천:",
    nextEyebrow: "여행 계획 메모",
    nextTitle: "이 가이드를 출발점으로 삼고, 예약 전 공식 정보를 확인하세요.",
    nextText: "영업시간, 교통, 날씨 위험, 이벤트 날짜는 바뀔 수 있습니다. 호텔, 티켓, 투어 예약 전 공식 관광 및 교통 정보를 확인하세요.",
    nextCard1Title: "여행 목적별 선택",
    nextCard1Text: "도시 음식, 사찰, 섬, 눈, 온천, 공예 마을은 각각 다른 여행 스타일에 어울립니다.",
    nextCard2Title: "시기와 교통 확인",
    nextCard2Text: "꽃 시즌, 눈길 루트, 페리, 지방 버스는 사전 계획이 특히 중요합니다.",
    nextCard3Title: "배려하는 여행",
    nextCard3Text: "사진 촬영, 쓰레기, 흡연, 신사 예절, 혼잡한 동네에서는 현지 안내를 따르세요.",
    footerBrand: "일본 도도부현 여행 가이드",
    footerText: "방일 여행자를 위한 독립 여행 계획 콘텐츠입니다. 예약 전 항상 최신 정보를 확인하세요.",
  },
  fr: {
    htmlLang: "fr",
    brand: "Guide du Japon par préfecture",
    languageLabel: "Langue",
    navRoutes: "Itinéraires",
    navPrefectures: "Préfectures",
    navPlanning: "Préparer",
    heroEyebrow: "Idées de voyage au Japon pour visiteurs internationaux",
    heroTitle: "Un guide pratique des 47 préfectures du Japon.",
    heroText:
      "Découvrez un lieu soigneusement choisi pour chaque préfecture, puis utilisez les idées d'itinéraires et les notes pratiques pour construire un voyage au-delà du parcours classique.",
    heroButton: "Explorer les 47 préfectures",
    summaryPrefectures: "idées de voyage par préfecture",
    summaryRegions: "langues disponibles",
    summarySpot: "itinéraires de départ",
    routesEyebrow: "Itinéraires suggérés",
    routesTitle: "Commencez par un itinéraire, puis choisissez les préfectures adaptées à votre style.",
    routesText:
      "Ces idées relient les cartes de préfectures à un vrai voyage. Elles restent larges afin de s'adapter au budget, à la saison et aux transports.",
    route1Label: "Premier voyage",
    route1Title: "Tokyo, Kyoto, Osaka et Nara",
    route1Text: "Une introduction équilibrée avec villes, temples, rues gourmandes et trains faciles.",
    route2Label: "Culture et côte",
    route2Title: "Kanazawa, Kyoto, Hiroshima et Miyajima",
    route2Text: "Un itinéraire plus lent pour jardins, artisanat, quartiers historiques et sanctuaire insulaire.",
    route3Label: "Ajout nature",
    route3Title: "Mont Fuji, Hokkaido ou Okinawa",
    route3Text: "Ajoutez montagnes, neige, onsen ou îles lorsque vous voulez dépasser les grandes villes.",
    pickerEyebrow: "Sélecteur de voyage",
    pickerTitle: "Explorez le Japon par préfecture.",
    pickerText:
      "Chaque carte présente un lieu recommandé et le type de voyageur auquel il convient. Recherchez par gastronomie, onsen, îles, châteaux, temples, nature ou paysages saisonniers.",
    searchLabel: "Recherche",
    searchPlaceholder: "Essayez Fuji, onsen, food, island...",
    countSingular: "préfecture affichée",
    countPlural: "préfectures affichées",
    cardIntro: "Un choix simple pour les voyageurs intéressés par",
    nextEyebrow: "Notes de préparation",
    nextTitle: "Utilisez ce guide comme point de départ, puis vérifiez les détails officiels avant de réserver.",
    nextText:
      "Horaires, transports, météo et dates d'événements peuvent changer. Avant de réserver hôtels, billets ou visites, vérifiez les sources officielles.",
    nextCard1Title: "Choisir selon le but du voyage",
    nextCard1Text: "Villes gourmandes, temples, îles, neige, onsen et villes d'artisanat conviennent à des styles différents.",
    nextCard2Title: "Vérifier saison et transport",
    nextCard2Text: "Fleurs saisonnières, routes enneigées, ferries et bus ruraux demandent souvent plus de préparation.",
    nextCard3Title: "Voyager avec respect",
    nextCard3Text: "Suivez les indications locales pour photos, déchets, zones fumeurs, sanctuaires et quartiers fréquentés.",
    footerBrand: "Guide du Japon par préfecture",
    footerText: "Contenu indépendant de préparation de voyage pour visiteurs internationaux. Vérifiez toujours les informations récentes avant de réserver.",
  },
  it: {
    htmlLang: "it",
    brand: "Guida del Giappone per prefettura",
    languageLabel: "Lingua",
    navRoutes: "Itinerari",
    navPrefectures: "Prefetture",
    navPlanning: "Pianifica",
    heroEyebrow: "Idee di viaggio in Giappone per visitatori internazionali",
    heroTitle: "Una guida pratica alle 47 prefetture del Giappone.",
    heroText:
      "Scopri un luogo scelto con cura per ogni prefettura, poi usa idee di itinerario e note pratiche per costruire un viaggio oltre il percorso più classico.",
    heroButton: "Esplora 47 prefetture",
    summaryPrefectures: "idee di viaggio per prefettura",
    summaryRegions: "lingue disponibili",
    summarySpot: "idee di itinerario iniziali",
    routesEyebrow: "Itinerari suggeriti",
    routesTitle: "Parti da un itinerario, poi scegli le prefetture adatte al tuo stile.",
    routesText:
      "Queste idee collegano le schede delle prefetture a un viaggio reale e sono abbastanza ampie da adattarsi a budget, stagione e trasporti.",
    route1Label: "Prima visita",
    route1Title: "Tokyo, Kyoto, Osaka e Nara",
    route1Text: "Un'introduzione equilibrata con città, templi, street food e collegamenti ferroviari semplici.",
    route2Label: "Cultura e costa",
    route2Title: "Kanazawa, Kyoto, Hiroshima e Miyajima",
    route2Text: "Un percorso più lento tra giardini, artigianato, quartieri storici e santuari sull'isola.",
    route3Label: "Aggiunta natura",
    route3Title: "Monte Fuji, Hokkaido o Okinawa",
    route3Text: "Aggiungi montagne, neve, onsen o isole quando vuoi andare oltre le grandi città.",
    pickerEyebrow: "Selettore di viaggio",
    pickerTitle: "Esplora il Giappone per prefettura.",
    pickerText:
      "Ogni scheda evidenzia un luogo consigliato e il tipo di viaggiatore a cui si adatta. Cerca cibo, onsen, isole, castelli, templi, natura e paesaggi stagionali.",
    searchLabel: "Cerca",
    searchPlaceholder: "Prova Fuji, onsen, food, island...",
    countSingular: "prefettura mostrata",
    countPlural: "prefetture mostrate",
    cardIntro: "Una scelta semplice per viaggiatori interessati a",
    nextEyebrow: "Note di pianificazione",
    nextTitle: "Usa la guida come punto di partenza, poi controlla i dettagli ufficiali prima di prenotare.",
    nextText:
      "Orari, trasporti, meteo e date degli eventi possono cambiare. Prima di prenotare hotel, biglietti o tour, verifica le fonti ufficiali.",
    nextCard1Title: "Scegli in base allo scopo",
    nextCard1Text: "Città gastronomiche, templi, isole, neve, onsen e città artigianali si adattano a stili diversi.",
    nextCard2Title: "Controlla periodo e trasporti",
    nextCard2Text: "Fioriture stagionali, percorsi innevati, traghetti e bus rurali richiedono spesso pianificazione extra.",
    nextCard3Title: "Viaggia con rispetto",
    nextCard3Text: "Segui le indicazioni locali per foto, rifiuti, aree fumatori, santuari e quartieri affollati.",
    footerBrand: "Guida del Giappone per prefettura",
    footerText: "Contenuto indipendente per pianificare viaggi in Giappone. Verifica sempre le informazioni aggiornate prima di prenotare.",
  },
};

const tagLabels = {
  en: {},
  ja: {
    nature: "自然",
    snow: "雪",
    flowers: "花",
    spring: "春",
    castle: "城",
    festival: "祭り",
    heritage: "世界遺産",
    temples: "寺院",
    slow: "ゆっくり旅",
    coast: "海岸",
    seafood: "海鮮",
    views: "絶景",
    history: "歴史",
    "old town": "古い町並み",
    temple: "寺院",
    hiking: "ハイキング",
    food: "食",
    autumn: "秋",
    shrines: "神社",
    onsen: "温泉",
    winter: "冬",
    "day trip": "日帰り",
    airport: "空港",
    city: "都市",
    "first trip": "初回旅行",
    island: "島",
    mountains: "山",
    scenery: "景色",
    gardens: "庭園",
    crafts: "工芸",
    museum: "博物館",
    family: "家族",
    fuji: "富士山",
    village: "村",
    lake: "湖",
    cycling: "サイクリング",
    nightlife: "夜遊び",
    "temple stay": "宿坊",
    pilgrimage: "巡礼",
    unique: "ユニーク",
    mythology: "神話",
    museums: "美術館",
    shrine: "神社",
    photo: "写真",
    valley: "渓谷",
    art: "アート",
    islands: "島",
    river: "川",
    gateway: "玄関口",
    ceramics: "陶磁器",
    harbor: "港",
    volcano: "火山",
    gorge: "峡谷",
    beach: "ビーチ",
    diving: "ダイビング",
  },
  zh: {
    nature: "自然",
    snow: "雪景",
    flowers: "花",
    spring: "春天",
    castle: "城堡",
    festival: "祭典",
    heritage: "遗产",
    temples: "寺庙",
    slow: "慢旅行",
    coast: "海岸",
    seafood: "海鲜",
    views: "景观",
    history: "历史",
    "old town": "古街",
    temple: "寺庙",
    hiking: "徒步",
    food: "美食",
    autumn: "秋天",
    shrines: "神社",
    onsen: "温泉",
    winter: "冬天",
    "day trip": "一日游",
    airport: "机场",
    city: "城市",
    "first trip": "首次旅行",
    island: "岛屿",
    mountains: "山",
    scenery: "风景",
    gardens: "庭园",
    crafts: "工艺",
    museum: "博物馆",
    family: "亲子",
    fuji: "富士山",
    village: "村落",
    lake: "湖",
    cycling: "骑行",
    nightlife: "夜生活",
    "temple stay": "寺宿",
    pilgrimage: "巡礼",
    unique: "独特",
    mythology: "神话",
    museums: "美术馆",
    shrine: "神社",
    photo: "摄影",
    valley: "溪谷",
    art: "艺术",
    islands: "岛屿",
    river: "河流",
    gateway: "门户",
    ceramics: "陶瓷",
    harbor: "港口",
    volcano: "火山",
    gorge: "峡谷",
    beach: "海滩",
    diving: "潜水",
  },
  ko: {
    nature: "자연",
    snow: "눈",
    flowers: "꽃",
    spring: "봄",
    castle: "성",
    festival: "축제",
    heritage: "유산",
    temples: "사찰",
    slow: "느린 여행",
    coast: "해안",
    seafood: "해산물",
    views: "전망",
    history: "역사",
    "old town": "옛 거리",
    temple: "사찰",
    hiking: "하이킹",
    food: "음식",
    autumn: "가을",
    shrines: "신사",
    onsen: "온천",
    winter: "겨울",
    "day trip": "당일치기",
    airport: "공항",
    city: "도시",
    "first trip": "첫 여행",
    island: "섬",
    mountains: "산",
    scenery: "풍경",
    gardens: "정원",
    crafts: "공예",
    museum: "박물관",
    family: "가족",
    fuji: "후지산",
    village: "마을",
    lake: "호수",
    cycling: "자전거",
    nightlife: "밤 문화",
    "temple stay": "사찰 숙박",
    pilgrimage: "순례",
    unique: "특별함",
    mythology: "신화",
    museums: "미술관",
    shrine: "신사",
    photo: "사진",
    valley: "계곡",
    art: "아트",
    islands: "섬",
    river: "강",
    gateway: "관문",
    ceramics: "도자기",
    harbor: "항구",
    volcano: "화산",
    gorge: "협곡",
    beach: "해변",
    diving: "다이빙",
  },
  fr: {
    nature: "nature",
    snow: "neige",
    flowers: "fleurs",
    spring: "printemps",
    castle: "château",
    festival: "festival",
    heritage: "patrimoine",
    temples: "temples",
    slow: "voyage lent",
    coast: "côte",
    seafood: "fruits de mer",
    views: "vues",
    history: "histoire",
    "old town": "vieille ville",
    temple: "temple",
    hiking: "randonnée",
    food: "gastronomie",
    autumn: "automne",
    shrines: "sanctuaires",
    onsen: "onsen",
    winter: "hiver",
    "day trip": "excursion",
    airport: "aéroport",
    city: "ville",
    "first trip": "premier voyage",
    island: "île",
    mountains: "montagnes",
    scenery: "paysages",
    gardens: "jardins",
    crafts: "artisanat",
    museum: "musée",
    family: "famille",
    fuji: "Fuji",
    village: "village",
    lake: "lac",
    cycling: "vélo",
    nightlife: "vie nocturne",
    "temple stay": "nuit au temple",
    pilgrimage: "pèlerinage",
    unique: "unique",
    mythology: "mythologie",
    museums: "musées",
    shrine: "sanctuaire",
    photo: "photo",
    valley: "vallée",
    art: "art",
    islands: "îles",
    river: "rivière",
    gateway: "porte d'entrée",
    ceramics: "céramique",
    harbor: "port",
    volcano: "volcan",
    gorge: "gorge",
    beach: "plage",
    diving: "plongée",
  },
  it: {
    nature: "natura",
    snow: "neve",
    flowers: "fiori",
    spring: "primavera",
    castle: "castello",
    festival: "festival",
    heritage: "patrimonio",
    temples: "templi",
    slow: "viaggio lento",
    coast: "costa",
    seafood: "pesce",
    views: "panorami",
    history: "storia",
    "old town": "centro storico",
    temple: "tempio",
    hiking: "escursioni",
    food: "cibo",
    autumn: "autunno",
    shrines: "santuari",
    onsen: "onsen",
    winter: "inverno",
    "day trip": "gita giornaliera",
    airport: "aeroporto",
    city: "città",
    "first trip": "primo viaggio",
    island: "isola",
    mountains: "montagne",
    scenery: "paesaggi",
    gardens: "giardini",
    crafts: "artigianato",
    museum: "museo",
    family: "famiglia",
    fuji: "Fuji",
    village: "villaggio",
    lake: "lago",
    cycling: "ciclismo",
    nightlife: "vita notturna",
    "temple stay": "soggiorno al tempio",
    pilgrimage: "pellegrinaggio",
    unique: "unico",
    mythology: "mitologia",
    museums: "musei",
    shrine: "santuario",
    photo: "foto",
    valley: "valle",
    art: "arte",
    islands: "isole",
    river: "fiume",
    gateway: "porta d'accesso",
    ceramics: "ceramica",
    harbor: "porto",
    volcano: "vulcano",
    gorge: "gola",
    beach: "spiaggia",
    diving: "immersioni",
  },
};

const grid = document.querySelector("#prefectureGrid");
const count = document.querySelector("#resultCount");
const search = document.querySelector("#prefectureSearch");
const regionButtons = document.querySelectorAll(".region-button");
const languageSelect = document.querySelector("#languageSelect");
let activeRegion = "all";
let currentLanguage = "en";
let lastSelectedLanguage = "en";

function t(key) {
  return translations[currentLanguage][key] || translations.en[key] || key;
}

function labelRegion(region) {
  return regionLabels[currentLanguage][region] || regionLabels.en[region] || region;
}

function labelTag(tag) {
  return tagLabels[currentLanguage]?.[tag] || tag;
}

function localPitch(englishPitch, spot, tags) {
  if (currentLanguage === "en") return englishPitch;

  const shownTags = tags.map(labelTag).join(" / ");
  const formats = {
    ja: `${spot}。${t("cardIntro")} ${shownTags}。`,
    zh: `${spot}。${t("cardIntro")} ${shownTags}。`,
    ko: `${spot}. ${t("cardIntro")} ${shownTags}.`,
    fr: `${spot}. ${t("cardIntro")} ${shownTags}.`,
    it: `${spot}. ${t("cardIntro")} ${shownTags}.`,
  };

  return formats[currentLanguage];
}

function updateStaticText() {
  document.documentElement.lang = t("htmlLang");
  document.title = t("brand");
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    const value = t(key);

    if (element.classList.contains("brand")) {
      element.lastChild.textContent = ` ${value}`;
    } else {
      element.textContent = value;
    }
  });
  search.placeholder = t("searchPlaceholder");
  regionButtons.forEach((button) => {
    button.textContent = labelRegion(button.dataset.region);
  });
}

function renderPrefectures() {
  const query = search.value.trim().toLowerCase();
  const filtered = prefectures.filter(([name, region, spot, pitch, tags]) => {
    const regionMatch = activeRegion === "all" || region === activeRegion;
    const searchableText = [
      name,
      labelRegion(region),
      regionLabels.en[region],
      spot,
      pitch,
      ...tags,
      ...tags.map(labelTag),
    ]
      .join(" ")
      .toLowerCase();
    return regionMatch && (!query || searchableText.includes(query));
  });

  count.textContent = `${filtered.length} ${filtered.length === 1 ? t("countSingular") : t("countPlural")}`;
  grid.innerHTML = filtered
    .map(
      ([name, region, spot, pitch, tags]) => `
        <article class="prefecture-card">
          <span class="prefecture-region">${labelRegion(region)}</span>
          <h3>${name}</h3>
          <p class="prefecture-spot">${spot}</p>
          <p>${localPitch(pitch, spot, tags)}</p>
          <div class="prefecture-tags">
            ${tags.map((tag) => `<span>${labelTag(tag)}</span>`).join("")}
          </div>
        </article>
      `,
    )
    .join("");
}

function changeLanguage() {
  currentLanguage = languageSelect.value;
  lastSelectedLanguage = currentLanguage;
  updateStaticText();
  renderPrefectures();
}

regionButtons.forEach((button) => {
  button.addEventListener("click", () => {
    activeRegion = button.dataset.region;
    regionButtons.forEach((item) => item.classList.remove("active"));
    button.classList.add("active");
    renderPrefectures();
  });
});

search.addEventListener("input", renderPrefectures);
languageSelect.addEventListener("change", changeLanguage);
languageSelect.addEventListener("input", changeLanguage);
setInterval(() => {
  if (languageSelect.value !== lastSelectedLanguage) {
    changeLanguage();
  }
}, 150);

updateStaticText();
renderPrefectures();
